spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/final_graduate?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    hikari:
      connection-init-sql: SET NAMES utf8mb4
dubbo:
  application:
    name: anfaoc-service
  registries:
    timeout: 4000
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名（数据库d_id匹配实体类dId）
  mapper-locations: classpath:mapper/*Mapper.xml #扫描mapper文件
  typeAliasesPackage: wzy.graduate.project.anfaoc.service.dao
logging:
  level:
    wzy.graduate.project.anfaoc.service...ssss.dao: debug

server:
  port: 8006
