dubbo:
  application:
    name: anfaoc-web
  registries:
    timeout: 4000
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: -1

redis:
  host: 127.0.0.1
  port: 6379
  jedis:
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 100
      # 连接池中的最小空闲连接
      max-idle: 10
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 100000
    # 连接超时时间（毫秒）
    timeout: 5000
    #默认是索引为0的数据库
    database: 0

thymeleaf:
  #资源路径
  prefix: classpath:/templates/
  #后缀
  suffix: .html
  servlet:
    content-type: text/html
  enabled: true
  encoding: UTF-8
  mode: HTML5
  #支持热部署
  cache: false

server:
  port: 8005